#pragma config(Sensor, in7,    distanceSensor1, sensorAnalog)
#pragma config(Sensor, in8,    distanceSensor2, sensorAnalog)
#pragma config(Sensor, dgtl1,  startingSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl2,  ballTriggerSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl4,  northPin,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  eastPin,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  southPin,          sensorDigitalIn)
#pragma config(Sensor, dgtl7,  westPin,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  front_right,    sensorDigitalIn)
#pragma config(Sensor, dgtl10, back_right,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, back_left,      sensorDigitalIn)
#pragma config(Sensor, dgtl12, front_left,     sensorDigitalIn)
#pragma config(Motor,  port2,           collectorServo, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           releaseServo,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "main.h"

const int ACCELERATION_STEP = 1;  // Incremental step for speed changes
const int MAX_BALLS = 1;

// Where we stopped: in the collecting phase. need to go forward and start collecting

task main()
{
  int ball_picked_count = 0;

  State current_state = IDLE;
  bool timer_started = false;

  /*
   * Note that speed values are always >=0. 'Negative speed' is accounted for by the direction.
   */
  int current_speed = 0;
  int target_speed = 0;

  int forward_duration = 2000;
  int turn_speed = 20; // Speed for turning in place

  int current_heading = 135;
  int playground_heading = 135;

  int search_bias = -1; // 1 for right first, -1 for left first
  int current_search_direction = 0;

  bool estop_debounce_active = false;

  while (true)
  {
    switch (current_state)
    {
      /*
       * Initialization state, waiting for user signal to start
       * Possible state changes: APPROACHING_TARGET_AREA
       */
      case IDLE:
        if (SensorValue(startingSwitch) == 0)  // Assuming starting switch is pressed to start the process
        {
          current_state = APPROACHING_TARGET_AREA;
        }
        break;

      /*
       * Approaching state, moving towards the detected ball for a set amount of time
       * Possible state changes: SEARCHING
       */
      case APPROACHING_TARGET_AREA:
        if (is_ball_detected() != 0)
        {
          if (is_ball_detected() == -1)
          {
            rotate(turn_speed, -1);
            wait1Msec(300);
          }
          else if (is_ball_detected() == 1)
          {
            rotate(turn_speed, 1);
            wait1Msec(300);
          }
          timer_started = false;  // Reset timer for next use
          move(0, 0);
          current_state = COLLECTING;
          break;
        }

        // if (SensorValue(front_right) == 0 || SensorValue(front_left) == 0)
        // {
        //   current_state = RECOVERY_FROM_BOUNDARY;
        //   timer_started = false;  // Reset timer for next use
        //   break;
        // }

        if (!timer_started)
        {
          clearTimer(T1);
          timer_started = true;
          current_speed = 0;
          target_speed = 250;
        }

        if (current_speed < target_speed)
        {
          current_speed += ACCELERATION_STEP;
          move(current_speed, 1);
        }

        if (time1[T1] >= forward_duration)
        {
          timer_started = false;
          current_speed = 0;
          move(current_speed, 0);
          current_state = SEARCHING;
        }
        break;

      /*
       * Searching state, looking for the ball using IR sensors and spinning in place
       * Possible state changes: COLLECTING
       */
      case SEARCHING:
        // Exit point: Ideal, detected ball. Stopping rotation and moving to collecting state
        if (is_ball_detected() != 0)
        {
          if (is_ball_detected() == -1)
          {
            rotate(turn_speed, -1);
            wait1Msec(300);
          }
          else if (is_ball_detected() == 1)
          {
            rotate(turn_speed, 1);
            wait1Msec(300);
          }
          timer_started = false;  // Reset timer for next use
          rotate(0, 0);
          current_state = COLLECTING;
          break;
        }

        // Entry point for searching state, start spinning to find the ball
        if (!timer_started)
        {
          clearTimer(T1);
          timer_started = true;
          rotate(turn_speed, search_bias);
          current_search_direction = search_bias;
        }

        // Stop for abit before reversing the turn
        int turn_duration = 600; // Time in ms to turn in one direction before switching
        int pause_duration = 500; // Time in ms to pause between direction changes
        if (time1[T1] >= turn_duration && time1[T1] < turn_duration + pause_duration)
        {
          rotate(0, 0);
        }
        else if (time1[T1] >= turn_duration + pause_duration && time1[T1] < turn_duration * 3.6 + pause_duration)
        {
          rotate(turn_speed, -search_bias);  // Reverse spin direction
          current_search_direction = -search_bias;
        }
        // Exit point: Failure, spun in both directions for 3 seconds each and still haven't found the ball. Stopping rotation and returning to idle state to try again
        else if (time1[T1] >= turn_duration * 3.6 + pause_duration && time1[T1] < turn_duration * 4.6 + pause_duration)
        {
          rotate(turn_speed, search_bias);  // Align back to center
          current_search_direction = search_bias;
        }
        else if (time1[T1] >= turn_duration * 4.6 + pause_duration)
        {
          timer_started = false;  // Reset timer for next use
          forward_duration = 1000;
          current_state = APPROACHING_TARGET_AREA; // Failure to find the ball, return to approaching state to try again
          wait1Msec(500); // Small delay before retrying
        }
        break;

      /*
       * Collecting state, activating mechanism to collect the ball
       * Possible state changes: NAVIGATING_TO_DEPOSIT
       */
      case COLLECTING:
        if (!timer_started)
        {
          clearTimer(T1);
          timer_started = true;
          start_ball_collector();
          current_speed = 0;
          target_speed = 50;
        }

        if (current_speed < target_speed)
        {
          current_speed += ACCELERATION_STEP;
          move(current_speed, 1);
        }

        if (time1[T1] >= 3000 || SensorValue(ballTriggerSwitch) == 0)
        {
          timer_started = false;  // Reset timer for next use
          current_speed = 0;
          move(current_speed, 0);
          if (SensorValue(ballTriggerSwitch) == 0)
            stop_ball_collector();
          current_state = NAVIGATING_TO_DEPOSIT;  // For testing, directly move to navigating state
        }
        break;

      /*
       * Navigating back to deposit state (can possibly just crash into the back)
       * Possible state changes: DEPOSITING
       */
      case NAVIGATING_TO_DEPOSIT:
        int heading_difference_from_playground = (playground_heading - get_current_heading() + 180) % 360 - 180; // Calculate difference and normalize to [-180, 180]        

        if (heading_difference_from_playground != 0)
        {
          // Rotate in the direction of the smaller angle
          int rotation_direction = (heading_difference_from_playground > 0) ? 1 : -1;
          rotate(turn_speed, rotation_direction);
          break;
        }
        else
        {
          wait1Msec(100); // Small delay to allow for any physical rotation to complete
        }
        
        if (SensorValue(back_right) != 0 || SensorValue(back_left) != 0)
        {
          move(100, -1); // Move backwards
        }
        else
        {
          move(0, 0); // Stop if not against the wall
          current_state = DEPOSITING;
        }
        break;

      /*
       * Depositing state, dropping the ball in the deposit area
       * Possible state changes: IDLE, APPROACHING_TARGET_AREA
       */
      case DEPOSITING:
        if (!timer_started)
        {
          clearTimer(T1);
          timer_started = true;
          open_ball_release();
        }

        if (time1[T1] >= 1500) // Wait for seconds to ensure the ball is released
        {
          timer_started = false;  // Reset timer for next use
          close_ball_release();
          ball_picked_count++;

          if (ball_picked_count >= MAX_BALLS)
          {
            current_state = IDLE;  // Return to idle after depositing all balls
          }
          else
          {
            current_state = APPROACHING_TARGET_AREA;  // Move to next ball
          }
        }      
        break;

      case RECOVERY_FROM_BOUNDARY:
        if (!timer_started)
        {
          clearTimer(T1);
          timer_started = true;
          move(-100, -1); // Move backwards to get away from the boundary
        }
        else if (time1[T1] >= 2000) // Move backwards for second
        {
          int heading_difference_from_playground = (playground_heading - get_current_heading() + 180) % 360 - 180; // Calculate difference and normalize to [-180, 180]        
          if (heading_difference_from_playground != 0)
          {
            // Rotate in the direction of the smaller angle
            int rotation_direction = (heading_difference_from_playground > 0) ? 1 : -1;
            rotate(turn_speed, rotation_direction);
            break;
          }
          else
          {
            move(0, 0); // Stop movement
            wait1Msec(100); // Small delay to allow for any physical rotation to complete
          }
          current_state = APPROACHING_TARGET_AREA; // Return to approaching state to try again
        }
        break;

      default:
        current_state = IDLE;
        break;
    }

    wait1Msec(10);  // Small delay to prevent overwhelming the processor
  }
}
